### ISSUE TITLE
Remove gradle cache and build files

### ISSUE THREAD

**Issue by colinmadere** [Kevin-Bernage/KBCalendar-Android#1]
Looks like a good start!

Things to remove to make project more clean and allow contirbutions (and add to your .gitignore):
.gradle
.idea
local.properties
*.iml

**Comment by Kevin-Bernage** [comment]
It's done for the .gitignore but it seems that i can't remove the .idea folder. In terminal, git remove only .idea files in .idea folder. Is it good for you or do you know how i can remove theses files ?
